version: 2
jobs:
  build:
    docker:
      - image: nutti/blender_addon_ci:v1.0
    branches:
      only:
        - master
        - develop
        - ci_testing
    steps:
      - checkout
      - run:
          name: Get required pip packages
          command: pip3 install -r requirements.txt
      - run:
          name: Copy add-on to Blender add-on's directory
          command: cp -r src/magic_uv ../blender-2.77-linux-glibc211-x86_64/2.77/scripts/addons
      - run:
          name: Check pylint
          command: bash tests/lint/pylint.sh src/magic_uv
      - run:
          name: Check pep8
          command: bash tests/lint/pep8.sh src/magic_uv
      - run:
          name: Run tests
          command: ../blender-2.77-linux-glibc211-x86_64/blender --factory-startup --background -noaudio --python tests/python/run_tests.py
      - run:
          name: Compress add-on as .zip file
          command: mkdir release && cd src && zip -r magic_uv.zip magic_uv && cd .. && mv src/magic_uv.zip release
      - store_artifacts:
          path: release
          destination: magic_uv